### ISSUE TITLE
Challenge #33 - WEkEO in a glance

### ISSUE THREAD

**Issue by EsperanzaCuartero** [esowc/challenges_2021#10]
# Challenge 33- WEkEO in a glance

> **Stream 3** - Visualize weather, climate and atmosphere

### Goal
The project aims at developing a prototype of a visualization tool based on the WEkEO* Platform.

*WEkEO is a joint ECMWF, EUMETSAT, MiO initiative to grant access to Copernicus datasets from different sources and incentive Users developing applications in the provided cloud frame. Computing facility will be provided by WEkEO.

### Mentors and skills
* **Mentors:** @stewartchrisecmwf @wekeo
* **Skills required:**
  * Data handling
  * Python programming 
  * Visualization
  * API and database interrogation

<br>

> <b> *Note: Challenge is funded by Copernicus. Only nationals from the European Union and ECMWF Member States are eligible to apply (see [Terms and Conditions](https://esowc.ecmwf.int/terms-and-conditions)).* </b>
<hr>

### Challenge description
**What data/system do you plan to use?**
A set of Copernicus data in WEkEO including CAMS, ERA5
and selected satellite (Sentinel5, Sentinel3).

**What is the current problem/limitation?**
Users have often expressed the need to visualize all data available in a defined time and geographical window for different purposes as:
 * Identify the useful datasets
 * Gather insights on a specific event
 * Have a tool for communication, outreach and training
Up to now, WEkEO offers a visualization platform allowing the overlay only selected datasets.

**What could be the solution?** 
Based on the expected user’s needs, a desirable feature would be to easily select and visualize all datasets of interest for a specific event (e.g. a wildfire, a specific weather pattern, an intense pollution) before downloading all or part of them. This may also address the need to identify in advance which datasets fit the needs and in which way the searched feature is visible.

**Some ideas for the implementation** 
Desired features:  

* Select a spatial window and a temporal frame 
* Report the available datasets
* Provide the option to select one or more variable and one timestep
* Map the selected ones on the spatial window for the selected time
* Produce an API to access/download the selected data

The proposed solution may gather from existing solutions.

<br>

<img src='https://user-images.githubusercontent.com/8168920/112646683-09509e80-8e48-11eb-9d6a-9e3dac6ac0d9.jpg' alt='ESoWC' align='center' width='80%'></img>

**Comment by jwagemann** [comment]
Hi,
join us for the **_ECMWF Summer of Weather Code Ask Me Anything_** session and learn all things ESoWC.

**When**: Wednesday, 24 March 2021 at 4 pm GMT

**What**: learn everything about ESoWC - how it works, the challenges this year, some tips for your proposal and listen to ESoWC experiences from previous participants

**How**: register [here](https://esowc.ecmwf.int/ama).
