### ISSUE TITLE
Challenge #31 : Grib Data example.

### ISSUE THREAD

**Issue by sylvielamythepaut** [esowc/challenges_2021#17]
Hi, 

I attach some data in GRIB and NetCDF
There are 5 parameters on 3 time steps.

2m temperature.
Total precipitation
low cloud cover
medium cloud cover
high cloud cover 

Hope everything is Ok .. 

Sylvie 
[data.zip](https://github.com/esowc/challenges_2021/files/6778368/data.zip)

**Comment by sylvielamythepaut** [comment]
@whatnick

**Comment by josuemtzmo** [comment]
Thanks Sylvie, I'm implementing the testing with `grib` files.
