### ISSUE TITLE
Challenge #14 - Atmospheric composition data comparison toolbox

### ISSUE THREAD

**Issue by EsperanzaCuartero** [esowc/challenges_2021#7]
# Challenge 14 - Atmospheric composition data comparison toolbox

> **Stream 1** - Software development for weather, climate and atmosphere

### Goal
Develop a set of reusable tools (with or without an interactive user interface) which will allow simple ad-hoc comparison of different atmospheric composition datasets.
The tools should include:
- unit conversion
- side-by-side visual comparison
- regridding
- time and geographic data aggregation
- computing and visualising of georeferenced statistics

### Mentors and skills
* **Mentors:** @miha-at-ecmwf @federicofierli1 @AntjeInness
* **Skills required:**
  * Good knowledge of Python and libraries to read, analyze and visualize atmospheric composition satellite and model data (numpy, eccodes, pandas, xarray, matplotlib)
  * Some knowledge of meteorological data formats (GRIB, NetCDF, HDF) and libraries to read and manipulate the data (ecCodes, netcdf, cdo, nco, ..)
  * Experience of either developing Jupyter notebooks or (even better) web-based dashboard applications

<br>

> <b> *Note: Challenge is funded by Copernicus. Only nationals from the European Union and ECMWF Member States are eligible to apply (see [Terms and Conditions](https://esowc.ecmwf.int/terms-and-conditions)).* </b>
<hr>

### Challenge description
**What is the current problem/limitation?**
Satellite and model atmospheric composition data are usually stored in different locations using different data formats with non-compatible metadata so it's not a trivial task to compare them. 

**What data/system do you plan to use?**
We would like to start with a few observed and modelled total column products, for example comparing GOME-2 ozone total column product (https://acsaf.org/offline_access.php) with ozone total column analyses from CAMS reanalysis (https://ads.atmosphere.copernicus.eu/cdsapp#!/dataset/cams-global-reanalysis-eac4) and the ozone monthly gridded dataset (https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-ozone-v1).

We would like to use the existing ECMWF, EUMETSAT and Copernicus infrastructure (Wekeo, Climate Data Store, Atmosphere Data Store, European Weather Cloud) as much as possible.

**What could be the solution?**
Many Python code examples already exists (1, 2) which demonstrate how to retrieve, read and understand each of the data products and convert them into a similar target format, like xarray Dataset object.

Some of the tasks that could be done under the project:
- making an inventory of the relevant sources of existing code
- review and consolidate the existing code and perform a gap analysis
- based on the findings develop the missing tools
- publish the tools as either well-documented collection of Jupyter notebooks or use them as a backend to a web application
- the tools and the application should not be limited to a specific platform

[1] https://gitlab.eumetsat.int/eumetlab/atmosphere/atmosphere
[2] https://github.com/CopernicusAtmosphere/jupyter-notebooks

This sketch is just one option. We welcome any other innovative proposals to address the stated challenge.

<br>

<img src='https://user-images.githubusercontent.com/8168920/112647275-9f84c480-8e48-11eb-8c60-142cbad22ab7.jpg' alt='ESoWC' align='center' width='80%'></img>

**Comment by jwagemann** [comment]
Hi,
join us for the **_ECMWF Summer of Weather Code Ask Me Anything_** session and learn all things ESoWC.

**When**: Wednesday, 24 March 2021 at 4 pm GMT

**What**: learn everything about ESoWC - how it works, the challenges this year, some tips for your proposal and listen to ESoWC experiences from previous participants

**How**: register [here](https://esowc.ecmwf.int/ama).

**Comment by abdrrahmmn** [comment]
Hey there, I am Abdurrahman Durmaz. I study Meteorological engineering at Istanbul Technical University (Bachelor`s degrees). Me and my classmate Halil Karakaya would be interested in this challenge. We have the relevant experience at reading, manipulating HDF and NetCDF data with Python. Furthermore, we have experience on web-based application with Django. 
Is there any spesific information that we should add to our proposal ?

**Comment by EsperanzaCuartero** [comment]
Dear Abdurrahman, thanks for your interest. The mentors of this challenge will be in contact as soon as possible. Best, Esperanza

**Comment by miha-at-ecmwf** [comment]
Dear Abdurrahman,

Many thanks for your interest our ESoWC challenge #14. 

As we have tried to explain in the proposal there are several existing Python code examples to read, process, compare and visualise our datasets. The problem is that they were developed by different people for different purposes (like training courses, for demonstrating a particular data processing technique or a specific software package ...).

The first goal of this challenge is to review and consolidate the code into logical and reusable modules. The second stage would be to then build a simple web data comparison tool to demonstrate the soundness of this approach.

Although we tried to sketch a possible solution (Jupyter notebooks with some interactive elements) we welcome any other innovative but realistic suggestion. The best proposal will demonstrate the understanding of the current issues and suggest a feasible and sustainable approach to tackle them.

Knowledge of Python and scientific data formats is definitely an advantage. Your experience with Django might be relevant depending on the details of your proposed technical solution.

To help us evaluate the proposals you should include specific technical details. We are not that keen to read long documents, just concise summary of what you plan to do. If you like, you could also include a small prototype to demonstrate your ideas.

Finally, if you would like to show us any other code that you've written (could be completely unrelated to this challenge) we would also be interested to hear about it.

Miha

**Comment by abdrrahmmn** [comment]
Dear Miha,

What we understand from this challenge is that, we are asked to write a program that can compare same parameters which is in various datasets. Thus, the outputs should be similar to the image below. Then, the program will present the plots of the desired parameter on a web page using the data sets which were specified by the user beforehand.

In this challenge, we can create an online web page with Django which can process the desired data sets and parameters in the background and present them. (Edited)

We have examined the jupyter notebooks above. However, it looks very confusing at first, so we have a few more questions:

- Are the datasets used on the old code concludes all of the datasets we need to use? Or are there any datasets to be added?
- Do we have to use these codes? So can we use them to write a ".py" file in a similar way ?
- Is there a list of data sets and parameters requested from us to compare? Or will only the parameters in old codes be used?

![cams_forecast](https://user-images.githubusercontent.com/55576210/113007920-4afe8380-917f-11eb-9e4c-074cc95e1136.png)

**Comment by abdrrahmmn** [comment]
@miha-at-ecmwf  Sorry but i need answer, there is limited time for apply. Thank you.

**Comment by miha-at-ecmwf** [comment]
Hi @abdrrahmmn ,

We see this as a bit of an open-ended challenge. We are suggesting some building blocks (like the code from Jupyter notebooks, xarray as a common data structure) but we wanted to leave to the candidates freedom to propose whatever they think would work best to achieve the stated goals.

If we would be only interested in Copernicus datasets the natural approach would be to use Wekeo (1) which offers unified API to many of the datasets. Unfortunately majority of the atmospheric composition satellite products are currently not available from the system.

During the coding phase we would like to build at least two examples to demonstrate that the system architecture is sound. My co-mentor colleague is away this week but I will speak to her next week and we will propose products which could be used in the first examples.

Miha

(1) https://wekeo.eu/

**Comment by Antjeinness** [comment]
Hi @abdrrahmmn<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabdrrahmmn&data=04%7C01%7Cantje.inness%40ecmwf.int%7Cb74aab271be44ff7119908d8f9a5bdc0%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637533837534617232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=clUU2tXFbvgYcg6hKUjH42vm47xoXoW%2BV8hEvVx%2BRpY%3D&reserved=0> ,


A good starting point could be a tool that makes use of IASI data and compares them to CAMS products. The aeris access point -

CATALOG – IASI portal (aeris-data.fr)<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fiasi.aeris-data.fr%2Fcatalog%2F&data=04%7C01%7CAntje.Inness%40ecmwf.int%7Cf794169923104ed35fce08d8fdccd85f%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637538403534929861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HwiVqWhZONBdN5heQoiSKxqC00d4xPDcOzsjkCLM5bk%3D&reserved=0> contains data for several species. The toolbox should be able to deal with different resolutions / geometries and vertical structure (e.g. using AKs or sampling functions). At this stage data are more demonstrators of the prototype than for a thorough validation exercise.


Alternatively, atmospheric composition data are also available from the AC-SAF, e.g. GOME-2 columns as NRT, offline and Data Record (that is interesting for comparison)

Access information of offline products (acsaf.org)<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Facsaf.org%2Foffline_access.php&data=04%7C01%7CAntje.Inness%40ecmwf.int%7Cf794169923104ed35fce08d8fdccd85f%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637538403534919904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zLdxMH4DKBPHuCnHWSYxLVjWnFZ%2FW3KOEnfqrSbE0h8%3D&reserved=0>

AC SAF user registration form<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Facsaf.org%2Fregistration_form.html&data=04%7C01%7CAntje.Inness%40ecmwf.int%7Cf794169923104ed35fce08d8fdccd85f%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637538403534929861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=owGPeRbBsGJhjhGWuSHRHOErzNg%2F%2FrXDc9uqOYSNy%2FU%3D&reserved=0>​


Antje



________________________________
